src/blueprints/profile.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
# import flask_login
from flask_login import login_user, logout_user, login_required, current_user


# NOTAS:


profile = Blueprint("profile", __name__, url_prefix="/profile")


@profile.route("/welcomeuser")
@login_required
def welcomeuser():
    print("<#################### welcomeuser ####################")
    user = ""
    tipo = ""
    if current_user.is_authenticated:
        user = current_user.get_name()  # Obtener el nombre del usuario
        tipo = current_user.get_tipo_usuario()
    print("#################### FIN (profile/welcome-user.html) ####################>")
    return render_template(
        "profile/welcome-user.html",
        user=user,
        tipo=tipo
    )


# endregion

src/blueprints/sales.py
import locale
# import flask
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
# importar modelos para query
from models.queries import (
    Read,
    CUD,
    ConsultaPIA,
    ConsultaCompanias,
    ConsultaIntermediarios,
)
# importar las excepciones
from models.exceptions import MyException
# importar las extenciones
from extensions import login_manager
#
from datetime import datetime
#
from flask_login import login_user, logout_user, login_required, current_user
#
import logging

# NOTAS:


# locale.setlocale(locale.LC_TIME, 'Spanish_Spain.1252')

sales = Blueprint("sales", __name__, url_prefix="/sales")


# region Agregar Ventas
@sales.route("/addsalesworker", methods=["GET", "POST"])
def addsalesworker():
    logging.info(f"Usuario autenticado: {current_user.id}, Rol: {current_user.tipo_usuario}")
    # Errores
    ErrorCantidad = False
    ErrorPrecio = False
    ErrorProductoInexistente = False
    # Capa 1: Verificar si el usuario está autenticado
    if current_user.is_authenticated:
        user_id = current_user.id if current_user.is_authenticated else 'guest'
        user_role = current_user.tipo_usuario
        print(f"User ID: {user_id}, User Role: {user_role}")
        if request.method == "POST":
            try:
                print("<#################### MakeSales ####################")
                sales_data = request.get_json()
                Entrada = []
                print("Sales Data Received:", sales_data)
                for i in range(len(sales_data)):
                    id = sales_data[i].get("id")
                    cantidad = sales_data[i].get("quantity")
                    print("ID>", id)  # El id
                    print("cantidad>", cantidad)
                    Entrada.append([int(id), int(cantidad)])
                #
                print("<==================== DATOS OBTENIDOS ====================")
                for producto in Entrada:
                    print(producto)
                print("========================================>")
                # Inicializar new como una lista de listas vacías
                tabla = [[] for _ in range(len(Entrada))]
                # Verificar que existe en la base de datos>
                print("Paso 1: verificar existencia del producto")
                ValidarExistencia = False
                for i in range(len(Entrada)):
                    ExisteProducto = Read(
                        """
                        SELECT 
                            proyecto.almacen.ID_PRODUCTO,
                            proyecto.almacen.PRECIO_UNITARIO,
                            proyecto.almacen.EXISTENCIAS
                        FROM proyecto.almacen 
                        WHERE proyecto.almacen.ESTATUS = 1 
                        AND proyecto.almacen.ID_PRODUCTO = ?
                        """,
                        (Entrada[i][0],),
                    )
                    tabla[i].append(ExisteProducto[0][0])
                    tabla[i].append(ExisteProducto[0][1])
                    tabla[i].append(ExisteProducto[0][2])
                    # Si un producto no existe, entonces terminamos el ciclo y el booleano ValidarExistencia es falso
                    if not ExisteProducto:
                        ValidarExistencia = False
                        break
                    # Si no hay errores entonces el booleano ValidarExistencia es verdadero
                    ValidarExistencia = True
                for producto in tabla:
                    print(producto)
                # Si los productos existen(Estan activos) y estan en la BD entonces>
                if ValidarExistencia == False:
                    raise MyException(
                        "ErrorEntrada",
                        "Se intentaron cambiar los datos.",
                    )
                if ValidarExistencia == True:
                    # Obtenemos la fecha actual
                    Auxiliar = datetime.now()
                    # Datos utiles para fecha
                    DiaA = Auxiliar.strftime("%d")  # Dia
                    MesA = Auxiliar.strftime("%B")  # Mes
                    AnioA = Auxiliar.strftime("%Y")  # Anio
                    # Imprimir
                    print(DiaA, MesA, AnioA)
                    # Encontrar ID_DIA en BD DIA
                    print("Paso 1: Encontrar ID_DIA en BD DIA")
                    Dia = int(
                        Read(
                            """
                        SELECT proyecto.dia.ID_DIA 
                        FROM proyecto.dia 
                        WHERE proyecto.dia.DIA = ?
                        """,
                            (DiaA,),
                        )[0][0]
                    )
                    # Encontrar ID_MES en BD MES
                    print("Paso 2: Encontrar ID_MES en BD MES")
                    Mes = int(
                        Read(
                            """
                        SELECT proyecto.mes.ID_MES 
                        FROM proyecto.mes 
                        WHERE proyecto.mes.MES = ?
                        """,
                            (MesA,),
                        )[0][0]
                    )
                    # Encontrar ID_ANIO en BD ANIO
                    print("Paso 3: Encontrar ID_ANIO en BD ANIO")
                    Anio = int(
                        Read(
                            """
                        SELECT proyecto.anio.ID_ANIO 
                        FROM proyecto.anio 
                        WHERE proyecto.anio.ANIO = ?
                        """,
                            (AnioA,),
                        )[0][0]
                    )
                    # Valores en 0
                    SumaCosto = 0  # Sumatoria del costo
                    SumaIva = 0  # Sumatoria del iva
                    TotalProductos = 0  # Sumatoria de la cantidad de productos
                    # Recorrer productos con un for
                    # Inicializar new como una lista de listas vacías
                    TablaDetalles = [[] for _ in range(len(Entrada))]
                    ErrorVenta = False
                    for i in range(len(Entrada)):
                        # Datos
                        """
                        tabla[i][0] = ID_Producto
                        tabla[i][1] = Costo Unitario
                        tabla[i][2] = Stock
                        Entrada[i][0] = ID_Producto
                        Entrada[i][1] = Cantidad de compra
                        """
                        if tabla[i][2] - Entrada[i][1] < 0:
                            print("Error en la venta")
                            ErrorVenta = True
                            break
                        else:
                            # Operaciones
                            Cost = (tabla[i][1]) * (Entrada[i][1])  # Costo por producto
                            IvaValue = Cost * 0.16  # Asumiendo que el IVA es del 16%
                            SumaCosto += Cost  # Sumar los costos por producto
                            SumaIva += round(IvaValue)  # Sumar los iva por producto
                            TotalProductos += Entrada[i][
                                1
                            ]  # Sumar la cantidad de productos
                            # Apartado en donde se agregar datos a array
                            TablaDetalles[i].append(Entrada[i][1])  # CANTIDAD
                            TablaDetalles[i].append(Cost)  # IMPORTE
                            TablaDetalles[i].append(round(IvaValue))  # IVA
                            TablaDetalles[i].append(tabla[i][0])  # ID_PRODUCTO
                    if ErrorVenta:
                        raise MyException(
                            "ErrorVenta",
                            "No hay existencias para reaelizar la venta.",
                        )
                    if not ErrorVenta:
                        # Datos
                        Total = SumaCosto + SumaIva  # Costo de la venta
                        print("Total venta:", SumaCosto)
                        print("Total iva:", SumaIva)
                        # BD
                        print("Total de productos vendidos:", TotalProductos)
                        print("Total con iva:", Total)
                        #
                        CUD(
                            """
                            INSERT INTO proyecto.ventas (CANTIDAD_VENTA, TOTAL, ESTATUS, ID_DIA, ID_MES, ID_ANIO) 
                            VALUES (?,?,1,?,?,?)
                            """,
                            (
                                int(TotalProductos),
                                float(Total),
                                int(Dia),
                                int(Mes),
                                int(Anio),
                            ),
                        )
                        id = int(Read("SELECT LAST_INSERT_ID() AS NewID;")[0][0])
                        #
                        print("ID-VENTA>", id)
                        for y in range(len(TablaDetalles)):
                            CUD(
                                """
                                INSERT INTO proyecto.detalles(CANTIDAD,IMPORTE,IVA,ESTATUS,ID_PRODUCTO,ID_VENTA) 
                                VALUES (?,?,?,1,?,?);
                                """,
                                (
                                    int(TablaDetalles[y][0]),
                                    float(TablaDetalles[y][1]),
                                    float(TablaDetalles[y][2]),
                                    int(TablaDetalles[y][3]),
                                    int(id),
                                ),
                            )
                        for z in range(len(TablaDetalles)):
                            RestarProductos = int(tabla[z][2] - Entrada[z][1])

src/templates/profile/profile.html
{% extends 'top navbar/top-navbar.html' %} {% block title %} profile {% endblock
    %} {%block content %}
    <form class="row g-3">
        <div class="col-md-6">
          <label for="inputEmail4" class="form-label">Email</label>
          <input type="email" class="form-control" id="inputEmail4">
        </div>
        <div class="col-md-6">
          <label for="inputPassword4" class="form-label">Password</label>
          <input type="password" class="form-control" id="inputPassword4">
        </div>
        <div class="col-12">
          <label for="inputAddress" class="form-label">Address</label>
          <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
        </div>
        <div class="col-12">
          <label for="inputAddress2" class="form-label">Address 2</label>
          <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
        </div>
        <div class="col-md-6">
          <label for="inputCity" class="form-label">City</label>
          <input type="text" class="form-control" id="inputCity">
        </div>
        <div class="col-md-4">
          <label for="inputState" class="form-label">State</label>
          <select id="inputState" class="form-select">
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div>
        <div class="col-md-2">
          <label for="inputZip" class="form-label">Zip</label>
          <input type="text" class="form-control" id="inputZip">
        </div>
        <div class="col-12">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
              Check me out
            </label>
          </div>
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
      </form>
    {% endblock %}

src/templates/profile/welcome-user.html
{% extends 'top navbar/top-navbar.html' %}
{% block title %} profile {% endblock%}

{%block content %}
<style>
  /*Desaparecer el scroll*/
  ::-webkit-scrollbar {
    display: none;
  }

  .btn-primary {
    width: 140px;
  }

  .user-color {
    background-image: linear-gradient(90deg, rgb(62, 90, 228), #4ccaf0da, #bde1ee 80%, rgb(62, 90, 228));
    background-clip: text;
    -webkit-text-fill-color: transparent;
    background-size: 200% 100%;
    /* Hace el degradado más largo para que se mueva */
    animation: gradient-scroll 4s ease-in-out infinite alternate;
    /* Alterna la animación para que vaya en ambas direcciones */
  }

  /* Animación para el efecto de desplazamiento */
  @keyframes gradient-scroll {
    0% {
      background-position: 0% 50%;
    }

    100% {
      background-position: 100% 50%;
    }
  }
</style>

<div class="container-fluid  animate__animated animate__fadeIn">

  <div class="d-flex justify-content-center align-items-center" style="height: 90vh">
    <div class="col-xl-10 d-flex flex-column align-items-center  text-center">
      <div class="row">
        <h1>Bienvenido a Fynex <br>
          <span class="text-capitalize user-color ">¡{{ user }}!</span>
        </h1>

        <p class="fs-5 my-2 ">¡Organiza tu trabajo y mejora tu desempeño con nosotros aquí!</p>
      </div>
      <a href="{{ url_for('sales.addsalesworker') }}" class="btn btn-primary  mt-2"><span data-section="welcome"
          data-value="shortcut">Entrar</span></a>
    </div>
  </div>

</div>


{% endblock %}